# Назначение: открывает frontend pod'ы как внутренний Kubernetes Service на порту 80.
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: wine-app
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
