# PVC для Qdrant — выделяет 2Gi хранилища в namespace wine-app
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage-pvc
  namespace: wine-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
