apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wine-shop
  namespace: argocd
spec:
  project: default

  source:
    repoURL: http://github.com/DarckShot/vector-wine-shop-DevOps.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: wine-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
